id = 6
title = "Cyber x Studio: Networking"
short = "Cyber x Studio: Networking" 
date = "Monday 11/8 6:00PM-8:00PM PT"
description = """ACM Cyber and Studio have come together to bring you a unique workshop about networking! Come back on a later date for more info!

RSVP on the Facebook Event
"""
link = ""
slides = ""