id = 6
title = "CTF After Dark"
short = "CTF After Dark" 
date = "5/17 8:00PM - 5/24 8:00PM PT"
description = """This is the moment you’ve been training for. Get ready for some high octane, mind-boggling tests of hacking skill! Collaborate with your friends in our beginner friendly Capture The Flag (CTF) competition. Challenges will be targeted at the skills that you’ve learned from our Spring workshops. Top teams get bragging rights as well as prizes. 

And don’t worry if you ever feel stuck or lonely. We’ll be in our discord channel, ready to answer any of your burning questions.
"""
link = ""
slides = ""
