id = 7
title = "CTF After Dark"
short = "CTF After Dark"
date = "TBD"
description = """This is the moment you’ve been training for. Get ready for some high octane, mind-boggling tests of hacking skill! Collaborate with your friends in our beginner friendly Capture The Flag (CTF) competition. Challenges will be targeted at the skills that you’ve learned from our Winter workshops. Top teams get bragging rights as well as prizes.
"""
link = ""
slides = ""