id = 1
title = "ACM Cyber Fall General Meeting"
short = "Cyber Fall GM" 
date = "Monday 10/4 6:00PM-8:00PM PT"
description = """Thinking of building an aimbot to get you out of bronze? ğŸ™ˆ Interested in learning about how hackers get their hands on private [UC] ğŸ‘€ information? Then ACM Cyber is just for you!! ğŸ˜
Come out to Cyber's Fall General Meeting on Monday, October 4th, at Franz Hall 2258A to learn more about what we do, meet our officers, make friends, and participate in a fun âœ¨Disney-themedâœ¨ cyber activity! No prior experience necessary!

RSVP on the Facebook Event
"""
link = "https://fb.me/e/RvlzR1Ns"
slides = ""